apiVersion: v1
kind: Service
metadata:
  name: ingress-serv
  namespace: ingress-nginx
spec:
  selector:
    app: my_app
  externalIPs:
  - 10.6.145.2
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
