apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: jenkins
spec:
  rules:
  - host: jenkins.local
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 8080
  - host: sonar.local
    http:
      paths:
      - path: /
        backend:
          serviceName: sonar
          servicePort: 9000
  - host: nexus.local
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus
          servicePort: 8081

