apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 4Gi                    
