apiVersion: v1
kind: Service
metadata:
  name: sonar
  namespace: jenkins
  labels:
    app: sonar
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9000
  selector:
    app: sonar                     
